# Description: Triggers the detection of the given load carriers and their filling level.

# Required. Pose frame for output poses (valid values are camera and external)
string pose_frame

# Optional
string region_of_interest_id

# Required
string[] load_carrier_ids

# Required only if reference frame = external and sensor is robot-mounted
geometry_msgs/Pose robot_pose

# Number of filling level cells to split detected load carriers
GridSize filling_level_cell_count

---

time timestamp

LoadCarrierWithFillingLevel[] load_carriers

rc_common_msgs/ReturnCode return_code
