# Description: Returns the configured regions of interest with the requested ids. If no ids are provided, all configured regions of interest are returned.

# Optional
string[] region_of_interest_ids

---

RegionOfInterest[] regions_of_interest

rc_common_msgs/ReturnCode return_code
